name: test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./install/action.yaml
      - name: Run lint and tests
        run: |
          pnpm run lint
          pnpm prettier:check
          pnpm run build
          pnpm run test

